---
name: CI Bmeme GKE-HELM Deployer container image
on:
  push:
    branches:
      - "*"
      - "!main"

env:
  registry: docker.io
  repository: bmeme/gke-helm-deployer

jobs:

  build:
    name: Build and test Bmeme GKE-HELM Deployer container image using Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the codebase.
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Lint Dockerfile
        id: lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
          config: .hadolint.yaml
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set tag
        id: vars
        run: echo "tag=$(cat ./Dockerfile | grep com.bmeme.project.version | awk -F\' '{print $2}')" >> $GITHUB_OUTPUT
      -
        name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: "linux/amd64"
          tags: |
            ${{ env.registry }}/${{ env.repository }}:${{ steps.vars.outputs.tag }}
            ${{ env.registry }}/${{ env.repository }}:latest
      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        id: trivy
        with:
          image-ref: ${{ env.registry }}/${{ env.repository }}:latest
          format: 'sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          output: 'trivy-results-gke-helm-deployer.sarif'
      -
        name: Upload Trivy scan results to GitHub Security tab
        id: trivy-upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-gke-helm-deployer.sarif'
      -
        name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: ${{ env.registry }}/${{ env.repository }}:latest
          severity-cutoff: critical
          fail-build: false
      -
        name: upload Anchore scan SARIF report
        id: scan-upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}


