---
name: Release Bmeme GKE-HELM Deployer container image
on:
  push:
    branches:
      - "main"

env:
  registry: docker.io
  repository: bmeme/gke-helm-deployer

jobs:

  build:
    name: Build and test Bmeme GKE-HELM Deployer container image using Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the codebase.
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image
        id: build
        run: |
          {
            TAG=$(cat Dockerfile| grep FROM | awk -F: '{print $2}');\
            \
            docker build \
              -t ${{ env.registry }}/${{ env.repository }}:${TAG} \
              -t ${{ env.registry }}/${{ env.repository }}:latest \
              -f ./Dockerfile .
          }
      -
        name: Push images to Docker Hub
        id: push
        run: |
          {
            TAG=$(cat Dockerfile| grep FROM | awk -F: '{print $2}');\
            docker push ${{ env.registry }}/${{ env.repository }}:${TAG}; \
            docker push ${{ env.registry }}/${{ env.repository }}:latest; \
          }
